version: "3.8"
services:
  mstpylib:
    container_name: mstpylib
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
    - type: bind
      source: .
      target: /local/mstpylib
    - type: bind
      source: ~/.kube
      target: /root/.kube
    command:
    - sleep
    - infinity
